import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api } from "../api/client";
import { Sparkles, Loader2 } from "lucide-react";
import type { AnalystAIReview as AIReviewType } from "../types";

interface Props {
  analyst: string;
  startDate?: string;
  endDate?: string;
}

export function AnalystAIReview({ analyst, startDate, endDate }: Props) {
  const [review, setReview] = useState<AIReviewType | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await api.getAnalystAIReview(analyst, {
        start_date: startDate,
        end_date: endDate,
      });
      setReview(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate review");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <h4 className="text-sm font-semibold flex items-center gap-2" style={{ color: "var(--theme-text-secondary)" }}>
          <Sparkles className="w-4 h-4" style={{ color: "var(--theme-accent)" }} />
          AI Performance Review
        </h4>
        <button
          onClick={generate}
          disabled={loading}
          className="px-3 py-1.5 rounded-lg text-xs font-medium transition-all flex items-center gap-1.5 disabled:opacity-50"
          style={{
            backgroundColor: "color-mix(in srgb, var(--theme-accent) 15%, transparent)",
            color: "var(--theme-accent)",
            border: "1px solid color-mix(in srgb, var(--theme-accent) 30%, transparent)",
          }}
        >
          {loading ? (
            <>
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-3.5 h-3.5" />
              {review ? "Regenerate" : "Generate Review"}
            </>
          )}
        </button>
      </div>

      {error && (
        <div className="rounded-lg p-3 mb-3 text-xs" style={{ backgroundColor: "rgba(239, 68, 68, 0.1)", color: "#EF4444", border: "1px solid rgba(239, 68, 68, 0.2)" }}>
          {error}
        </div>
      )}

      {review ? (
        <div className="prose prose-sm max-w-none" style={{ color: "var(--theme-text-secondary)" }}>
          <div
            className="text-sm leading-relaxed [&_h2]:text-base [&_h2]:font-bold [&_h2]:mb-2 [&_h2]:mt-4 [&_h3]:text-sm [&_h3]:font-semibold [&_h3]:mb-1.5 [&_h3]:mt-3 [&_ul]:ml-4 [&_ul]:list-disc [&_li]:mb-1 [&_strong]:font-semibold"
            style={{
              ["--tw-prose-headings" as string]: "var(--theme-text-primary)",
              ["--tw-prose-bold" as string]: "var(--theme-text-primary)",
            }}
          >
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{review.review}</ReactMarkdown>
          </div>
          <p className="text-[10px] mt-3 opacity-60">
            Generated by {review.provider} • {new Date(review.generated_at).toLocaleString("id-ID")}
          </p>
        </div>
      ) : !loading ? (
        <div
          className="rounded-lg p-6 text-center text-xs"
          style={{
            backgroundColor: "color-mix(in srgb, var(--theme-surface-raised) 50%, transparent)",
            color: "var(--theme-text-muted)",
            border: "1px dashed var(--theme-surface-border)",
          }}
        >
          Click "Generate Review" to get an AI-powered performance analysis
        </div>
      ) : null}
    </div>
  );
}
